### ISSUE TITLE
Bmstu-logo not found

### ISSUE THREAD

**Issue by Yokud** [Orianti/bmstu-latex-template#12]
После обновления на новую версию класса при компиляции выдает ошибку: "File "bmstu-logo" not found". Отдельное скачивание лого и размещение в папке класса не избавляет от проблемы

**Comment by Orianti** [comment]
Была ошибка при загрузке пакета в TeX Live, я обратился к ответственному за это лицу, ошибку исправили. На данный момент всё должно работать. Нужно обновить пакет через tlmgr.

**Comment by Yokud** [comment]
В MiKTeX эта ошибка тоже есть

**Comment by Orianti** [comment]
> В MiKTeX эта ошибка тоже есть

Разработчик MiKTeX пока не отвечает на мой запрос. Как будут изменения — сообщу.

**Comment by Orianti** [comment]
Файл `bmstu-logo.pdf` добавлен в пакет в MiKTeX (https://miktex.org/packages/bmstu/files).
