### ISSUE TITLE
Некорректное отображение страницы списка литературы в содержании

### ISSUE THREAD

**Issue by BelloMak** [Orianti/bmstu-latex-template#17]
Доброго времени суток, в ходе активного использования Вашего шаблона был обнаружен следующий баг: в содержании номер страницы списка литературы не совпадает с действительностью (то есть, например,  список литературы начинается на 17 странице, а в содержании написано, что на 18). Есть предположение, что такое поведение класса вызвано вставкой в документ pdf страниц с помощью пакета pdfpages (в 3 документах, в которых вставлялись pdf страницы, наблюдалось данное поведение). 

Для исправления бага предлагаю изменить в файле bmstu-biblio.sty строки 

	\printbibliography[title=СПИСОК ИСПОЛЬЗОВАННЫХ ИСТОЧНИКОВ]
	\addcontentsline{toc}{chapter}{СПИСОК ИСПОЛЬЗОВАННЫХ ИСТОЧНИКОВ}

на следующую, обладающую схожим функционалом:

	 \printbibliography[heading=bibintoc,title={СПИСОК ИСПОЛЬЗОВАННЫХ ИСТОЧНИКОВ}]

В рамках моего проекта данное изменение решило проблему.

**Comment by Orianti** [comment]
Возможно проблема дублирует #13?

**Comment by BelloMak** [comment]
Кстати да, похоже, что дублирует. При этом установлена последняя версия Вашего пакета.

**Comment by Orianti** [comment]
Это исправление пока в ветке develop, а не master, поэтому его нет в последней версии сборки.

**Comment by BelloMak** [comment]
Понял, закрываю задачу.
